---
- hosts: web
  become: true
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: ok GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name:  repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io  

    - name: check secu docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Grant access Ubuntu
      apt:
        name: ""
        state:
        force_apt_get: "yes"

    - name: Get git Repository
      apt:
        name: ""
        state:
        force_apt_get: "yes"

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted

